# configuration for https://travis-ci.org/bitcoinj/bitcoinj
sudo: false
dist: xenial
language: java
matrix:
  include:
  - jdk: openjdk11
install: true
script:
  - ./gradlew clean buildCI

notifications:
  irc:
    channels: "irc.freenode.net#bitcoinj"
    skip_join: true
